language: rust
rust:
- nightly

cache:
  apt: true
  directories:
      - ./compile/libraries/

matrix:
    include:
        - env: NAME=hex TARGET=arm-unknown-linux-gnueabihf LINKER=arm-linux-gnueabihf-gcc HOST=arm-linux-gnueabihf SSL_HOST=linux-armv4 PACKAGE=$NAME-arm.tar.gz
          addons:
            apt:
              packages:
                - gcc-arm-linux-gnueabihf
                - libc6-armhf-cross
                - libc6-dev-armhf-cross
        - env: NAME=hex TARGET=x86_64-unknown-linux-musl LINKER=musl-gcc HOST=x86_64-linux-musl SSL_HOST=linux-x86_64 PACKAGE=$NAME-musl.tar.gz
          addons:
             apt:
               packages:
                 - musl
        #- env:
          #  - NAME=hex
          #  - TARGET=x86_64-unknown-linux-gnu
          #  - PACKAGE=$NAME-x86_64.tar.gz

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup target add $TARGET || true
  - |
    if [ -n "$LINKER" ]; then
      mkdir -p ~/.cargo
      echo >> ~/.cargo/config
      echo "[target.$TARGET]" >> ~/.cargo/config
      echo "linker = \"$LINKER\"" >> ~/.cargo/config
    fi
before_install:
    - ./compile/compile_libraries.sh

script:
    - ./compile/compile.sh

before_deploy:
- tar -czf $PACKAGE -C target/$TARGET/release/ hex-cli hex-zyklop hex-web

deploy:
  provider: releases
  api_key:
    secure: fOg8sbu5scUE/A5bxkbeNE/1HNRKHxJRSQF2ZqXEO6I4Zquzjtijyod8cIXnjuHMhzjHvhSGWW99VE7Ypa2P7kDVol0AoqQdKUaFiBXlPmtxBFtlJnMDQi1uuTdC4cA3k7H3p15Bk/yZQIlcirBO0jcajo049Ki3Vnwvol1tYBhzoHkzYhN507kQ65k+iOhRGNlIj1I9K4twFO292mKkF0ZVGqgDMDege/KhyVET+pxEFUVJVbumLNUF7Kdfs3ogfRo/IIhv0lZv7k5k35I1K1qJBofHfSlL7FMXYQHAPh/IGEW++nUEzu5c5J3Vv0Lrci6AOLLBD2UTGTmr3s4vcZn004ebvdd+8gDi1NZITsAKi6t8Fb7/hBubgEy1O2bi54bfyWhSurVAsXmJqkfAaqCpq8P4ddvsDZRlVAD67INcWPjAeKggtvWtA6DXDIsxnFxTBg0NOvVKMHXdJoE5+M9iU85YJQKoXJSAn74nFq5D9oGqZQn30thevpmIKCXyf5mVTZcCr5inDx5H6EGv6zMgllvs5T8lu7KweFXPoOuvQqbkf14foWScel8vk2Zc/yCP5g+FhJPeOjhZfqfgYlSxWdw+qZSOrhd8fhEf9xol/GXa8Ij2t96ehDpWoNinvGZt1pl4moROeCyUHsh5px+MfHRolKtXG0V1B0wsZJo=
  file: ${PACKAGE}
  skip_cleanup: true
  on:
    tags: true
    repo: bytesnake/hex
