[package]
name = "hex-cli"
version = "0.1.0"
authors = ["Lorenz Schmidt <bytesnake@mailbox.org>"]

[dependencies]
getopts = "0.2"

[dependencies.hex-music-container]
path = "../music-container/"

[dependencies.hex-database]
path = "../database/"
default_features = false
features = ["rusqlite"]
