host = "192.168.1.9"

[server]
port = 2794

[music]
data_path = "/tmp/music/data/"
db_path  = "/tmp/music/music.db"

[webserver]
path = "../frontend/build/"
port = 8081

[sync]
port = 8004
name = "Computer Lorenz"
sync_all = true
