[server]
host = "127.0.0.1"
port = 2794

[music]
data_path = "/tmp/music/data/"
db_path  = "/tmp/music/music.db"

[webserver]
path = "../frontend/build/"
host = "127.0.0.1"
port = 8081

[sync]
mode = "all"
name = "Hex Karlsgraben"
