host = "127.0.0.1"

[server]
port = 2794

[music]
data_path = "/opt/music/data/"
db_path  = "/opt/music/music.db"

[webserver]
path = "../frontend/build/"
port = 8081

[sync]
port = 8004
name = "Computer Lorenz"
sync_all = true
