[package]
name = "hex-sync"
version = "0.1.0"
authors = ["Lorenz Schmidt <bytesnake@mailbox.org>"]

[dependencies]
tokio = "0.1"
tokio-io = "0.1"
futures = "0.1"
bytes = "0.4"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"

[dependencies.hex-database]
path = "../database"
features = ["serde"]
