[package]
name = "nightly-worker"
version = "0.1.0"
authors = ["Lorenz Schmidt <bytesnake@mailbox.org>"]
edition = "2018"

[dependencies]
chrono = "0.4"

[dependencies.hex-database]
path = "../database/"

[dependencies.hex-conf]
path = "../conf/"
